version: "3.8"
services:
  recommendation-redis:
    container_name: recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: jieunchc/recommendation-redis
    ports:
      - "6379:6379"
  recommendation-database:
    container_name: recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: jieunchc/recommendation-database
    environment:
      - MARIADB_DATABASE=recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
